//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaroChecklist.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Primary {
            get {
                return ((bool)(this["Primary"]));
            }
            set {
                this["Primary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Glaxon_Vandal {
            get {
                return ((bool)(this["Glaxon_Vandal"]));
            }
            set {
                this["Glaxon_Vandal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ignis_Wraith {
            get {
                return ((bool)(this["Ignis_Wraith"]));
            }
            set {
                this["Ignis_Wraith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Gorgon {
            get {
                return ((bool)(this["Prisma_Gorgon"]));
            }
            set {
                this["Prisma_Gorgon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Grakata {
            get {
                return ((bool)(this["Prisma_Grakata"]));
            }
            set {
                this["Prisma_Grakata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Grinlock {
            get {
                return ((bool)(this["Prisma_Grinlock"]));
            }
            set {
                this["Prisma_Grinlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Tetra {
            get {
                return ((bool)(this["Prisma_Tetra"]));
            }
            set {
                this["Prisma_Tetra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Quanta_Vandal {
            get {
                return ((bool)(this["Quanta_Vandal"]));
            }
            set {
                this["Quanta_Vandal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Supra_Vandal {
            get {
                return ((bool)(this["Supra_Vandal"]));
            }
            set {
                this["Supra_Vandal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Vulkar_Wraith {
            get {
                return ((bool)(this["Vulkar_Wraith"]));
            }
            set {
                this["Vulkar_Wraith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Mara_Detron {
            get {
                return ((bool)(this["Mara_Detron"]));
            }
            set {
                this["Mara_Detron"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Angstrum {
            get {
                return ((bool)(this["Prisma_Angstrum"]));
            }
            set {
                this["Prisma_Angstrum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Twin_Gremlins {
            get {
                return ((bool)(this["Prisma_Twin_Gremlins"]));
            }
            set {
                this["Prisma_Twin_Gremlins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Viper_Wraith {
            get {
                return ((bool)(this["Viper_Wraith"]));
            }
            set {
                this["Viper_Wraith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Zylok {
            get {
                return ((bool)(this["Zylok"]));
            }
            set {
                this["Zylok"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Halikar_Wraith {
            get {
                return ((bool)(this["Halikar_Wraith"]));
            }
            set {
                this["Halikar_Wraith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Dual_Cleavers {
            get {
                return ((bool)(this["Prisma_Dual_Cleavers"]));
            }
            set {
                this["Prisma_Dual_Cleavers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Obex {
            get {
                return ((bool)(this["Prisma_Obex"]));
            }
            set {
                this["Prisma_Obex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Dual_Decurion {
            get {
                return ((bool)(this["Prisma_Dual_Decurion"]));
            }
            set {
                this["Prisma_Dual_Decurion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Prisma_Veritux {
            get {
                return ((bool)(this["Prisma_Veritux"]));
            }
            set {
                this["Prisma_Veritux"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Opticor_Vandal {
            get {
                return ((bool)(this["Opticor_Vandal"]));
            }
            set {
                this["Opticor_Vandal"] = value;
            }
        }
    }
}
